### ISSUE TITLE
request database backend 

### ISSUE THREAD

**Issue by zenmisael** [ngekoding/admin-panel#17]
any chance to implement database backend??

**Comment by ngekoding** [comment]
For what?

**Comment by zenmisael** [comment]
for multiple users login

**Comment by ngekoding** [comment]
I think that are some complex things to do, and currently I don't have any plan (time) for that.

**Edit:**
Sorry I think I commenting on [whatsapp-api-tutorial's repository](https://github.com/ngekoding/whatsapp-api-tutorial), so it is admin-panel. Haha
So, for this admin-panel was built for the use of front-end only (UI), there is no correlation for the backend.

**Comment by zenmisael** [comment]
ok mas.. noted that..
terimakasih banyak
